disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - weak_delegate
opt_in_rules: # some rules are only opt-in
  - force_unwrapping
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - last_where
  - implicit_return
  - legacy_multiple
  - legacy_random
  - multiline_arguments
  - operator_usage_whitespace
  - strict_fileprivate
  - toggle_bool
  - unused_import
  - yoda_condition
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift


# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast:
  severity: error

force_unwrapping:
  severity: error

force_try:
  severity: error

line_length:
  warning: 180
  ignores_comments: true

colon:
  severity: error

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 800

large_tuple:
   - 3
   - 4
