# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create ipa like LRM"
  lane :build do |options|
    begin
      cocoapods(repo_update: true)
    rescue => ex
      # re-raise the exception unless it's something we're OK with ignoring
      raise ex unless ex.message.include?('Podfile.lock')
      sh("rm ../Podfile.lock")
      cocoapods(repo_update: true)
      UI.important('cocoapods failed, retrying...')
    end
    increment_build_number
    gym(
      scheme: "DataDomeSDKTestApp",
      configuration: options[:configuration],
      include_bitcode: false,
      export_method: 'ad-hoc',
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic"
      }
    )
  end
end
